Alizeh shop
Scout-NU/lavan-beauty pull request #26
Opened 2024-11-14 21:03 UTC by alizehzaidi

Merge request

2024-11-18 01:46 UTC, stephanierongone requested changes
good overall! just a couple small changes

2024-11-18 01:46 UTC, stephanierongone commented on src/pages/shop/Shop.css
> +.night-stars-container {
I would try to combine some of these classes into one, just to make your file a little more condensed!

2024-11-18 01:46 UTC, stephanierongone commented on src/pages/shop/Shop.js
> +                                        <img className="star1-image" src={} alt="star 1" />
making things like the stars container a reusable component could come in handy later down the road

2024-11-21 23:40 UTC, ananyar807 commented on src/pages/AboutUs.css
did you mean to add the aboutUs css file to this branch?

2024-11-26 23:00 UTC, merged